export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILED = 'PURCHASE_FAILED';